Repository CUK-CRUSH/Duett-Server, pull requests merged in 2024-06, with the labels that each got.

#8 Feat: Image API 구현
  src/main/java/Dino/Duett/config/EnvBean.java
  src/main/java/Dino/Duett/domain/image/dto/ImageDto.java
  src/main/java/Dino/Duett/domain/image/entity/Image.java
  src/main/java/Dino/Duett/domain/image/exception/ImageException.java
  src/main/java/Dino/Duett/domain/image/repository/ImageRepository.java
  src/main/java/Dino/Duett/domain/image/service/ImageService.java
  src/main/java/Dino/Duett/global/exception/ErrorCode.java
  src/main/resources/application-gcs.yml
  src/test/java/Dino/Duett/test/controller/LoginTest.java
  src/test/java/Dino/Duett/test/service/ImageServiceTest.java
  src/test/java/Dino/Duett/utils/TestUtil.java
Labels: enhancement

#16 Docs/login api #15
  .github/workflows/build.yml
  src/main/java/Dino/Duett/config/security/SecurityConfig.java
  src/main/java/Dino/Duett/domain/authentication/controller/AuthenticationController.java
  src/main/java/Dino/Duett/domain/authentication/controller/LoginController.java
  src/main/java/Dino/Duett/domain/authentication/dto/LoginDto.java
Labels: documentation

#17 Feat: Login API 명세 추가
  .github/workflows/build.yml
  src/main/java/Dino/Duett/config/security/SecurityConfig.java
  src/main/java/Dino/Duett/domain/authentication/controller/AuthenticationController.java
  src/main/java/Dino/Duett/domain/authentication/controller/LoginController.java
  src/main/java/Dino/Duett/domain/authentication/dto/LoginDto.java
  src/test/java/Dino/Duett/test/component/GmailReaderTest.java
Labels: documentation

#19 Feat: 사용자 가입여부 확인 API
  src/main/java/Dino/Duett/domain/authentication/controller/AuthenticationController.java
  src/main/java/Dino/Duett/domain/authentication/dto/CheckMemberDto.java
  src/main/java/Dino/Duett/domain/member/service/MemberService.java
  src/test/java/Dino/Duett/test/controller/AuthenticationControllerTest.java
  src/test/java/Dino/Duett/utils/TestUtil.java
Labels: enhancement

#22 [Feat] 마이페이지 프로필 정보 조회 및 등록 API
  src/main/java/Dino/Duett/domain/mood/dto/request/MoodCreateRequest.java
  src/main/java/Dino/Duett/domain/mood/dto/response/MoodResponse.java
  src/main/java/Dino/Duett/domain/mood/entity/Mood.java
  src/main/java/Dino/Duett/domain/mood/service/MoodService.java
  src/main/java/Dino/Duett/domain/music/controller/MusicController.java
  src/main/java/Dino/Duett/domain/music/dto/request/MusicCreateRequest.java
  src/main/java/Dino/Duett/domain/music/dto/request/MusicUpdateRequest.java
  src/main/java/Dino/Duett/domain/music/dto/response/MusicResponse.java
  src/main/java/Dino/Duett/domain/music/entity/Music.java
  src/main/java/Dino/Duett/domain/music/exception/MusicException.java
  src/main/java/Dino/Duett/domain/music/service/MusicService.java
  src/main/java/Dino/Duett/domain/profile/controller/ProfileApi.java
  src/main/java/Dino/Duett/domain/profile/controller/ProfileCardController.java
  src/main/java/Dino/Duett/domain/profile/controller/ProfileController.java
  src/main/java/Dino/Duett/domain/profile/dto/request/ProfileInfoRequest.java
  src/main/java/Dino/Duett/domain/profile/dto/request/ProfileIntroRequest.java
  src/main/java/Dino/Duett/domain/profile/dto/request/ProfileMusicRequest.java
  src/main/java/Dino/Duett/domain/profile/dto/response/ProfileCardResponse.java
  src/main/java/Dino/Duett/domain/profile/dto/response/ProfileCardSummaryResponse.java
  src/main/java/Dino/Duett/domain/profile/dto/response/ProfileInfoResponse.java
  src/main/java/Dino/Duett/domain/profile/dto/response/ProfileIntroResponse.java
  src/main/java/Dino/Duett/domain/profile/entity/Profile.java
  src/main/java/Dino/Duett/domain/profile/service/ProfileCardService.java
  src/main/java/Dino/Duett/domain/profile/service/ProfileService.java
  src/main/java/Dino/Duett/domain/tag/exception/TagException.java
  src/main/java/Dino/Duett/global/enums/LimitConstants.java
  src/main/java/Dino/Duett/global/exception/ErrorCode.java
  src/main/java/Dino/Duett/global/util/Validator.java
  src/test/java/Dino/Duett/domain/profile/controller/ProfileControllerTest.java
  src/test/java/Dino/Duett/utils/TestUtil.java
Labels: enhancement

#26 [Feat] 프로필 완성여부 조회 API의 완료 조건 수정
  src/main/java/Dino/Duett/domain/TestController.java
  src/main/java/Dino/Duett/domain/mood/controller/MoodController.java
  src/main/java/Dino/Duett/domain/profile/controller/ProfileCardController.java
  src/main/java/Dino/Duett/domain/profile/entity/Profile.java
  src/main/java/Dino/Duett/domain/profile/enums/GenderType.java
  src/main/java/Dino/Duett/domain/profile/service/ProfileCardService.java
  src/main/java/Dino/Duett/domain/profile/service/ProfileUnlockService.java
  src/main/java/Dino/Duett/global/enums/LimitConstants.java
Labels: enhancement

#27 Fix: 회원가입 프로필 생성되지 않아서 null point exception 발생 수정
  src/main/java/Dino/Duett/domain/profile/service/ProfileService.java
  src/main/java/Dino/Duett/domain/signup/dto/SignUpReq.java
  src/main/java/Dino/Duett/global/exception/GlobalExceptionHandler.java
  src/test/java/Dino/Duett/domain/search/controller/SearchControllerTest.java
  src/test/java/Dino/Duett/test/controller/AuthenticationControllerTest.java
  src/test/java/Dino/Duett/test/controller/SignUpControllerTest.java
  src/test/java/Dino/Duett/test/service/MemberServiceTest.java
  src/test/java/Dino/Duett/utils/TestUtil.java
Labels: bug
